### PR TITLE
refactor(vue): revise select, stories & test

### PR DESCRIPTION
**Pull request by iamdin**

### CODE REVIEW

**Comment by Omikorin** [comment]
Let's use that new API for defineComponent. You were right and we can achieve two things at once

**Comment by iamdin** [comment]
@Omikorin That's great！I will refactor in the next commit. By the way，does that mean we will refactoring all components with the new way？

**Comment by Omikorin** [comment]
Yeah, we'll do it for all the components. With [Vue 2 EOL](https://blog.vuejs.org/posts/vue-2-eol), I think there will be more users using min. v3.3 that we need anyway.

I'll commit here one change to Presence to show you something.

**Comment by Omikorin** [comment]
Okay, please look at #1785. Files: `accordion.tsx`, `accordion-item.tsx`, `accordion-item-content.tsx`.

We changed a method for using presence from `<Presence>` to `usePresence` / `usePresenceProps` and API directly in the component

**Comment by iamdin** [comment]
Thank you so much for the showcase！

**Comment by Omikorin** [comment]
I hope Function Signature won't break anything in the meantime hah

**Comment by iamdin** [comment]
@Omikorin  Thank you! I've been busy with work recently, will be back later

**Pull request merged**
