### PR TITLE
fix(vue): add id props and improve state exposition

### LINKED ISSUE #825: [Vue]: Unique ID doesn't work in SSR
Hey again,

Stumbled on an issue while using various components. The unique id created with the `useId()` utility within the component and passed to the machine isn't unique when using SSR. In addition, any `id` prop passed to the component is ignored. Doing a brief scan, it looks like some components are also still missing the `id` prop.

As of now, it seems the only solutions are either:

1. Wrap every component in `<ClientOnly>`.

2. Develop an SPA.

These reproductions show some issues stemming from this. In the `Select` repro, the second menu position is not where it should be. In the `Editable` repro, the active styling remains on the second input when focusing between the two inputs. In either one, wrapping the components in `ClientOnly` or adding `ssr: false` to the `nuxt.config.ts` should fix the issues and create a different id as expected (which you can see in the DOM).

https://stackblitz.com/edit/nuxt-starter-xzqjnc?file=app.vue

https://stackblitz.com/edit/nuxt-starter-g6mate?file=nuxt.config.ts

Hope this helps. Perhaps there's another solution I'm unaware of as well.

### LINKED ISSUE #913: [Vue]: Allow for exposure of machine API to `v-slot` for needed components
### Description

Part of an overall cleanup with the Vue package is being able to expose the individual component's machine API through the `v-slot` so that state such as boolean checks or selected values can be accessed by the user to then apply to custom structures within each component's wrapper.

If not immediately, considering to also apply the `expose` method with the APIs for added flexibility.

### Additional Information

Related to #905

### PR DESCRIPTION
**Pull request by Shyrro**
BREAKING CHANGE: Update exposed context types and remove unnecessary expose calls

This PR contains :

- Addition of id prop to all components ( Closes #825 )
- Update to types to be as close as possible to the machine
- Addition fo slot props for exposure (update slot props when needed and expose when needed) ( Closes #913 , #905 )

### CODE REVIEW

**Comment by cschroeter** [comment]
```json
"id": {
    "type": "string",
    "isRequired": true,
    "description": "The unique identifier of the machine."
  },
```

The generated types, in this case the accordion are not 100% correct. The `id` should be optional. We achieve this in React / Solid doing sth like this:

```tsx
export type UseAccordionProps = Optional<accordion.Context, 'id'>
```

**Comment by jiblett1000** [comment]
Hey ya'll. Just wondering if this PR is taking into account the recent release of Vue 3.3 and specifically being able to use imported types in SFC? I just upgraded and the exported types from Ark don't seem to be compatible for some reason. 

Just curious as this could be a huge time saver as I wouldn't need to re-write all of the props in my custom components, but just import an extend the ones from Ark instead.

**Comment by Shyrro** [comment]
Hey @jiblett1000 

This PR is not related, as the SFC types are only available under SFC's. We use TSX to build our Vue components so we don't have the same issues as we can already use Typescript how we want. 

The exported types are pure typescript so you can reuse them in your own `defineProps` if needed. 

Could you elaborate a little bit more on what you mean by "exportes types don't seem compatible for some reason", what errors do you have etc?

Thanks

**Comment by jiblett1000** [comment]
Hey @Shyrro I'm happy to create an issue for this if need be. This is where I'm importing / using the type:

```ts
import type { NumberInputProps } from "@ark-ui/vue";

interface Props {
  label: string;
  id?: string;
  paddingRight?: number;
  paddingLeft?: number;
}

const props = defineProps<NumberInputProps & Props>();
```

I modified an existing stackblitz to show the error.... although, I'm getting a different error there than I am locally. 

https://stackblitz.com/edit/nuxt-starter-3jzcrb?file=components%2FChildDialog.vue

**Pull request merged**
